site_name: Zheming Gao
site_url: https://www.zheminggao.site/
;repo_url: https://tonygaobasketball/tonygaobasketball.github.io/


nav:
- Home: index.md
- Publications: pub.md
- Teaching: teach.md
- Research: research.md 

theme:
    name: mkdocs
    nav_style: dark
    <!--highlightjs: true-->
    hljs_languages:
        - yaml
        - rust
;theme:
;  name: material
;  palette:
;    - scheme: default
;      toggle:
;        icon: material/toggle-switch-off-outline
;        name: Switch to dark mode
;    - scheme: slate
;      toggle:
;        icon: material/toggle-switch
;        name: Switch to light mode-->

markdown_extensions:
;  - toc:
;      permalink: True
  - attr_list

copyright: 
    Copyright &copy; Zheming Gao 2021
